### ISSUE TITLE
Errors - Kali linux - -A param

### ISSUE THREAD

**Issue by M3noetius** [SpiderLabs/Responder#120]
#sudo ./Responder.py -I wlan0 -A
`[i] Responder is in analyze mode. No NBT-NS, LLMNR, MDNS requests will be poisoned.
Traceback (most recent call last):
  File "./Responder.py", line 263, in <module>
    main()
  File "./Responder.py", line 182, in main
    from poisoners.LLMNR import LLMNR
  File "filepath/Responder-master/poisoners/LLMNR.py", line 45, in <module>
    IsICMPRedirectPlausible(settings.Config.Bind_To)
  File "filepath/Responder-master/poisoners/LLMNR.py", line 39, in IsICMPRedirectPlausible
    if x != "127.0.0.1" and IsOnTheSameSubnet(x,IP) is False:
  File "filepath/Responder-master/utils.py", line 50, in IsOnTheSameSubnet
    ipaddr = int(''.join([ '%02x' % int(x) for x in ip.split('.') ]), 16)
ValueError: invalid literal for int() with base 10: 'fe80::1%wlan0'
`

**Comment by sumaoqing123** [comment]
temporarily, you can edit /etc/resolv.conf, and delete the line starts with 'fe80'

**Comment by kawaxi** [comment]
thanks for the information @sumaoqing123
