### ISSUE TITLE
Responder Error in Kali

### ISSUE THREAD

**Issue by ChambersPIT74** [SpiderLabs/Responder#132]
Responder Error in Kali

Exception happened during processing of request from ('192.168.0.107', 62793)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/share/responder/poisoners/LLMNR.py", line 81, in handle
----------------------------------------
Exception happened during processing of request from ('192.168.0.107', 62793)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/usr/share/responder/poisoners/LLMNR.py", line 81, in handle
    'AnalyzeMode': '0',
  File "/usr/share/responder/utils.py", line 236, in SavePoisonersToDb
    'AnalyzeMode': '0',
  File "/usr/share/responder/utils.py", line 236, in SavePoisonersToDb
    res = cursor.execute("SELECT COUNT(*) AS count FROM Poisoned WHERE Poisoner=? AND SentToIp=? AND ForName=? AND AnalyzeMode=?", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
OperationalError: no such table: Poisoned

**Comment by 0xsauby** [comment]
Responder development has moved to https://github.com/lgandx/Responder
Pull the latest code and see if you still have the same issue.

**Comment by ChambersPIT74** [comment]
This worked Thanks, 0xsauby
