### ISSUE TITLE
OperationalError: database is locked

### ISSUE THREAD

**Issue by Techno-Fox** [SpiderLabs/Responder#159]
Was using responder on a test lab network and came to an error. 
The command : responder -FPwfdbr -I eth0

The error : 

Exception happened during processing of request from ('10.65.2.86', 58111)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/usr/share/responder/poisoners/LLMNR.py", line 81, in handle
    'AnalyzeMode': '0',
  File "/usr/share/responder/utils.py", line 242, in SavePoisonersToDb
    res = cursor.execute("SELECT COUNT(*) AS count FROM Poisoned WHERE Poisoner=? AND SentToIp=? AND ForName=? AND AnalyzeMode=?", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
OperationalError: database is locked

P.S. Thank you

**Comment by Techno-Fox** [comment]
Just got a lot more 

Exception happened during processing of request from----------------------------------------
 (----------------------------------------
Exception happened during processing of request from
 '10.65.2.81', 5353('10.65.2.81'Exception happened during processing of request from (Exception happened during processing of request from'10.65.2.81' ()
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
, '10.65.2.81'59946)
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
, 57953)
    self.RequestHandlerClass(request, client_address, self)
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
, 5353----------------------------------------
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
)
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
Exception happened during processing of request from ('10.65.2.81', 55947)
    self.RequestHandlerClass(request, client_address, self)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.RequestHandlerClass(request, client_address, self)
    self.handle()
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
  File "/usr/share/responder/poisoners/MDNS.py", line 73, in handle
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.finish_request(request, client_address)
    self.finish_request(request, client_address)
    self.handle()
    self.handle()
  File "/usr/share/responder/poisoners/LLMNR.py", line 81, in handle
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    'AnalyzeMode': '0',
  File "/usr/share/responder/poisoners/LLMNR.py", line 81, in handle
  File "/usr/share/responder/utils.py", line 246, in SavePoisonersToDb
    'AnalyzeMode': '0',
  File "/usr/share/responder/utils.py", line 242, in SavePoisonersToDb
    self.RequestHandlerClass(request, client_address, self)
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    'AnalyzeMode': '0',
  File "/usr/share/responder/utils.py", line 242, in SavePoisonersToDb
    self.handle()
OperationalError: database is locked
    self.handle()
  File "/usr/share/responder/poisoners/LLMNR.py", line 81, in handle
    res = cursor.execute("SELECT COUNT(*) AS count FROM Poisoned WHERE Poisoner=? AND SentToIp=? AND ForName=? AND AnalyzeMode=?", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
OperationalError: database is locked
  File "/usr/share/responder/poisoners/MDNS.py", line 73, in handle
--------------------------------------------------------------------------------
    res = cursor.execute("SELECT COUNT(*) AS count FROM Poisoned WHERE Poisoner=? AND SentToIp=? AND ForName=? AND AnalyzeMode=?", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
OperationalError: database is locked
    'AnalyzeMode': '0',
    'AnalyzeMode': '0',
  File "/usr/share/responder/utils.py", line 246, in SavePoisonersToDb

  File "/usr/share/responder/utils.py", line 242, in SavePoisonersToDb
    res = cursor.execute("SELECT COUNT(*) AS count FROM Poisoned WHERE Poisoner=? AND SentToIp=? AND ForName=? AND AnalyzeMode=?", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
    cursor.execute("INSERT INTO Poisoned VALUES(datetime('now'), ?, ?, ?, ?)", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
OperationalError: database is locked
 ----------------------------------------
OperationalError: database is locked
 --------------------------------------------------------------------------------

----------------------------------------
 ----------------------------------------
Exception happened during processing of request from ('10.65.2.81', 137)
 ----------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
Exception happened during processing of request fromException happened during processing of request from  ('10.65.2.81'(, '10.65.2.81', 137137))

Traceback (most recent call last):
Traceback (most recent call last):
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.handle()
  File "/usr/share/responder/poisoners/NBTNS.py", line 75, in handle
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.RequestHandlerClass(request, client_address, self)
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    'AnalyzeMode': '0',
  File "/usr/share/responder/utils.py", line 242, in SavePoisonersToDb
    self.RequestHandlerClass(request, client_address, self)
    res = cursor.execute("SELECT COUNT(*) AS count FROM Poisoned WHERE Poisoner=? AND SentToIp=? AND ForName=? AND AnalyzeMode=?", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
OperationalError: database is locked
----------------------------------------
    self.handle()
    self.handle()
  File "/usr/share/responder/poisoners/NBTNS.py", line 75, in handle
  File "/usr/share/responder/poisoners/NBTNS.py", line 75, in handle
    'AnalyzeMode': '0',
    'AnalyzeMode': '0',
  File "/usr/share/responder/utils.py", line 242, in SavePoisonersToDb
  File "/usr/share/responder/utils.py", line 242, in SavePoisonersToDb
    res = cursor.execute("SELECT COUNT(*) AS count FROM Poisoned WHERE Poisoner=? AND SentToIp=? AND ForName=? AND AnalyzeMode=?", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
    res = cursor.execute("SELECT COUNT(*) AS count FROM Poisoned WHERE Poisoner=? AND SentToIp=? AND ForName=? AND AnalyzeMode=?", (result['Poisoner'], result['SentToIp'], result['ForName'], result['AnalyzeMode']))
OperationalError: database is locked
OperationalError: database is locked
