### ISSUE TITLE
struct parsing error in MDNS poisoner

### ISSUE THREAD

**Issue by byt3bl33d3r** [SpiderLabs/Responder#47]
Hi,
While testing the new changes out I've noticed this exception occurring a lot:
```python
Exception happened during processing of request from ('10.9.138.189', 5353)
Traceback (most recent call last):
[Analyze mode: NBT-NS] Request by 10.9.142.218 for WPAD, ignoring
  File "/usr/lib64/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
[Analyze mode: LLMNR] Request by 169.254.155.18 for wpad, ignoring
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/home/byt3bl33d3r/Tools/responder/poisoners/MDNS.py", line 46, in handle
[Analyze mode: LLMNR] Request by 10.9.142.185 for isaproxysrv, ignoring
    Request_Name = Parse_MDNS_Name(data)
  File "/home/byt3bl33d3r/Tools/responder/poisoners/MDNS.py", line 27, in Parse_MDNS_Name
    NameLen = struct.unpack('>B',data[0])[0]
IndexError: string index out of range
```

**Comment by byt3bl33d3r** [comment]
Heres a packet capture of the relevant MDNS traffic https://mega.co.nz/#!iZhThJbJ!9fCMvb-a0_C8N559I1Avs-rZIsNeO1qrVleedS81_Tg

**Comment by lgandx** [comment]
Thanks!
