### ISSUE TITLE
Error while parsing SMB dialect

### ISSUE THREAD

**Issue by byt3bl33d3r** [SpiderLabs/Responder#48]
This seems to be occurring a lot too:
```python
[*] [NBT-NS] Poisoned answer sent to 10.9.130.194 for name ISAPROXYSRV (service: Workstation/Redirector)
----------------------------------------
Exception happened during processing of request from ('10.9.137.84', 57438)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib64/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib64/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/home/byt3bl33d3r/Tools/responder/servers/SMB.py", line 233, in handle
    Body = SMBNegoKerbAns(Dialect=Parse_Nego_Dialect(data))
  File "/home/byt3bl33d3r/Tools/responder/servers/SMB.py", line 65, in Parse_Nego_Dialect
    if Dialect[10] == "NT LM 0.12":
IndexError: tuple index out of range
```

**Comment by lgandx** [comment]
Do you have a pcap trace of this? It might be an old client, like Novell trying to connect.

**Comment by byt3bl33d3r** [comment]
@lgandx I don't have access to that network anymore unfortunately so can't give you a packet capture, I can however give you a hexdump of the packets that caused the errors
```
2015-08-04 09:55:33 10.9.135.126 [LLMNR] Poisoned request for name darhoade-ms
Exception on Parse_Nego_Dialect! Packet hexdump:
00000000:  00 00 00 db ff 53 4d 42 72 00 00  00 00 08 43 c8 00 00 00 00 00 00   |.....SMBr.....C.......|
00000016:  00 00 00 00 00 00 00 00 00 00 00  00 01 00 00 b8 00 02 50 43 20 4e   |..................PC N|
0000002C:  45 54 57 4f 52 4b 20 50 52 4f 47  52 41 4d 20 31 2e 30 00 02 4d 49   |ETWORK PROGRAM 1.0..MI|
00000042:  43 52 4f 53 4f 46 54 20 4e 45 54  57 4f 52 4b 53 20 31 2e 30 33 00   |CROSOFT NETWORKS 1.03.|
00000058:  02 4d 49 43 52 4f 53 4f 46 54 20  4e 45 54 57 4f 52 4b 53 20 33 2e   |.MICROSOFT NETWORKS 3.|
0000006E:  30 00 02 4c 41 4e 4d 41 4e 31 2e  30 00 02 57 69 6e 64 6f 77 73 20   |0..LANMAN1.0..Windows |
00000084:  66 6f 72 20 57 6f 72 6b 67 72 6f  75 70 73 20 33 2e 31 61 00 02 4c   |for Workgroups 3.1a..L|
0000009A:  4d 31 2e 32 58 30 30 32 00 02 44  4f 53 20 4c 41 4e 4d 41 4e 32 2e   |M1.2X002..DOS LANMAN2.|
000000B0:  31 00 02 4c 41 4e 4d 41 4e 32 2e  31 00 02 53 61 6d 62 61 00 02 4e   |1..LANMAN2.1..Samba..N|
000000C6:  54 20 4c 41 4e 4d 41 4e 20 31 2e  30 00 02 4e 54 20 4c 4d 20 30 2e   |T LANMAN 1.0..NT LM 0.|
000000DC:  31 32 00                                                             |12.|
```

```
2015-08-04 09:55:31 10.9.133.197 [LLMNR] Poisoned request for name usrpkutil01
Exception on Parse_Nego_Dialect! Packet hexdump:
00000000:  00 00 00 db ff 53 4d 42 72 00 00  00 00 08 43 c8 00 00 00 00 00 00   |.....SMBr.....C.......|
00000016:  00 00 00 00 00 00 00 00 00 00 00  00 01 00 00 b8 00 02 50 43 20 4e   |..................PC N|
0000002C:  45 54 57 4f 52 4b 20 50 52 4f 47  52 41 4d 20 31 2e 30 00 02 4d 49   |ETWORK PROGRAM 1.0..MI|
00000042:  43 52 4f 53 4f 46 54 20 4e 45 54  57 4f 52 4b 53 20 31 2e 30 33 00   |CROSOFT NETWORKS 1.03.|
00000058:  02 4d 49 43 52 4f 53 4f 46 54 20  4e 45 54 57 4f 52 4b 53 20 33 2e   |.MICROSOFT NETWORKS 3.|
0000006E:  30 00 02 4c 41 4e 4d 41 4e 31 2e  30 00 02 57 69 6e 64 6f 77 73 20   |0..LANMAN1.0..Windows |
00000084:  66 6f 72 20 57 6f 72 6b 67 72 6f  75 70 73 20 33 2e 31 61 00 02 4c   |for Workgroups 3.1a..L|
0000009A:  4d 31 2e 32 58 30 30 32 00 02 44  4f 53 20 4c 41 4e 4d 41 4e 32 2e   |M1.2X002..DOS LANMAN2.|
000000B0:  31 00 02 4c 41 4e 4d 41 4e 32 2e  31 00 02 53 61 6d 62 61 00 02 4e   |1..LANMAN2.1..Samba..N|
000000C6:  54 20 4c 41 4e 4d 41 4e 20 31 2e  30 00 02 4e 54 20 4c 4d 20 30 2e   |T LANMAN 1.0..NT LM 0.|
000000DC:  31 32 00                                                             |12.|
```

**Comment by lgandx** [comment]
Yep, it's an old client trying to connect to Responder.

**Comment by lgandx** [comment]
Actually, it looks like a Samba4 client. Added support for this.

**Comment by byt3bl33d3r** [comment]
@lgandx awesome thanks!
