### ISSUE TITLE
Responder exception

### ISSUE THREAD

**Issue by cclements** [SpiderLabs/Responder#77]
Hello,

I received this error while running responder earlier:

```
**----------------------------------------
Exception happened during processing of request from ('172.28.20.18', 42040)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/opt/pentest/tools/Responder/servers/MSSQL.py", line 140, in handle
    if data[0] == "\x10":
IndexError: string index out of range
----------------------------------------
**
```

**Comment by ad0nis** [comment]
I am receiving the same error on a pentest this afternoon. (Sorry for the "me too", but I wanted to put some weight on the bug.)

**Comment by joesmith82** [comment]
I received a similar error with SMB:

[SMB] Requested Share     : \\MACHINENAME\IPC$
----------------------------------------
Exception happened during processing of request from ('192.168.1.5', 55126)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/opt/Responder/servers/SMB.py", line 305, in handle
    data = self.request.recv(1024)
error: [Errno 104] Connection reset by peer

**Comment by lgandx** [comment]
Nothing to worry about.. These are debug errors.

**Comment by b3b0** [comment]
@lgandx are you saying that

```
Exception happened during processing of request from ('192.168.1.5', 55126)
Traceback (most recent call last):
File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
self.finish_request(request, client_address)
File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
self.RequestHandlerClass(request, client_address, self)
File "/usr/lib/python2.7/SocketServer.py", line 655, in init
self.handle()
File "/opt/Responder/servers/SMB.py", line 305, in handle
data = self.request.recv(1024)
error: [Errno 104] Connection reset by peer
```

is considered a debug error? Would this indicate that the vulnerability is patched on the victim side?
