### ISSUE TITLE
color undefined error

### ISSUE THREAD

**Issue by kd4zay** [SpiderLabs/Responder#86]
Hi,
I found the following error when using the following switches.
/Responder.py -I eth0 --lm -f -A

Just wanted to let you guys know awsome script thank you!

----------------------------------------
Exception happened during processing of request from ('192.168.1.103', 60913)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 596, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 331, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 652, in __init__
    self.handle()
  File "/root/Responder/poisoners/NBTNS.py", line 59, in handle
    Finger = fingerprint.RunSmbFinger((self.client_address[0],445))
  File "/root/Responder/fingerprint.py", line 67, in RunSmbFinger
    print color("[!] ", 1, 1) +" Fingerprint failed"
NameError: global name 'color' is not defined
----------------------------------------

**Comment by lgandx** [comment]
Solved, thanks for your report!

**Comment by kd4zay** [comment]
FYI also getting the following error when you hit control-C

[+] Exiting...
Exception in thread Thread-1 (most likely raised during interpreter
shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "./Responder.py", line 141, in serve_LLMNR_poisoner
<type 'exceptions.TypeError'>: 'NoneType' object is not callable


On Wed, Jun 8, 2016 at 2:37 PM, lgandx <notifications@github.com> wrote:

> Solved, thanks for your report!
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/SpiderLabs/Responder/issues/86#issuecomment-224703584>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ALMsuwfhgx5n4bhX1ROer7rz-omTbeBxks5qJxntgaJpZM4Iv4NE>
> .
>



-- 

*Jesus Cabrera*

*336 Mount Joy RD | **Hampshire, TN. 38461*

Phone 931-446-7199 E-Mail jcabrera@jcabrera.info
