### ISSUE TITLE
Error on exit

### ISSUE THREAD

**Issue by kd4zay** [SpiderLabs/Responder#87]
Also getting the following error when you send a control-c

[+] Exiting...
Exception in thread Thread-1 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
  File "/usr/lib/python2.7/threading.py", line 754, in run
  File "./Responder.py", line 141, in serve_LLMNR_poisoner
<type 'exceptions.TypeError'>: 'NoneType' object is not callable

**Comment by lgandx** [comment]
Thanks!
